server:
  #端口
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  thymeleaf:
    cache: false  #清除缓存
    prefix: classpath:/templates/
    mvc:
      static-path-pattern: /admin/**
  txcos:
    secretId: AKIDiEVYP1RZ1GDwTiv5tSnt2yrXx97rrkvs
    secretKey: wf9OPAnDUXieNq4xc5LTM3Xq05yd9QUN
    bucket: ap-shanghai
    bucketName: school-1251531734
    path: https://school-1251531734.cos.ap-shanghai.myqcloud.com
    prefix: exam
  servlet:
    multipart:
      max-file-size: 5MB # 单个文件的最大值
      max-request-size: 5MB # 上传文件总的最大值

      #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/yun?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      #最大连接数，默认10
      maximum-pool-size: 10
      #从连接池返回的连接的自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      #连接超时时间，默认3000（30秒）
      connection-timeout: 30000
      #测试是否可用的查询语句
      connection-test-query: SELECT 1
  redis:
    timeout: 10000
    #数据库索引
    database: 0
    # 服务器地址
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        #最大连接数,默认8
        max-active: 1024
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 10000ms
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 5
        #连接超时时间
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #消息确认回调
    publisher-confirm-type: correlated
    #消息失败回调
    publisher-returns: true



#Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    #自动驼峰命名
    map-underscore-to-camel-case: false
    ## mybatis sql  打印（方法接口所在的包，不是Mapper.xml所在的包）
  type-aliases-package: com.example.server.pojo


logging:
  level:
    com.example.server.mapper: debug
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#


# JWT配置

# JWT配置    //注解要是拿不到，就主要看配置文件命名是否一致

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yun-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer